In [6]:
import numpy as np

array = np.array([1,2,3,4,5])

array

array([1, 2, 3, 4, 5])

In [16]:
array_1 = np.arange(2,9.0)
array_1

array([2., 3., 4., 5., 6., 7., 8.])

In [21]:
array_2 = np.arange(2,9,.1)
array_2

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
       7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
       8.5, 8.6, 8.7, 8.8, 8.9])

In [23]:
array_3 = np.linspace(2,9,3)
array_3

array([2. , 5.5, 9. ])

In [25]:
array_4 = np.linspace(2,9,20)
array_4

array([2.        , 2.36842105, 2.73684211, 3.10526316, 3.47368421,
       3.84210526, 4.21052632, 4.57894737, 4.94736842, 5.31578947,
       5.68421053, 6.05263158, 6.42105263, 6.78947368, 7.15789474,
       7.52631579, 7.89473684, 8.26315789, 8.63157895, 9.        ])

In [26]:
array_5 = np.arange(2,20,4)
array_5

array([ 2,  6, 10, 14, 18])

In [29]:
print(array_5[0], array_5[2], array_5[-1], array_5[-5])

2 10 18 2


In [30]:
array_6 = np.arange(0,15)
array_6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
array_6[0:14:3]

array([ 0,  3,  6,  9, 12])

In [36]:
array_6[2:5] = 25
array_6

array([ 0,  1, 25, 25, 25,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
array_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
array_2d.shape

(3, 4)

In [57]:
array_1_2d = np.arange(100).reshape(10,10)
array_1_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
array_1_2d[2:5,::2]

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [62]:
array_2_2d = np.arange(30).reshape(6,5)
array_2_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [63]:
mask = array_2_2d < 20
mask

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [64]:
array_2_2d[mask]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
array_3_2d = np.arange(9).reshape(3,3)
array_3_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])